<a href="https://colab.research.google.com/github/basilegupov/First_repo/blob/master/DSHW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
# виведіть його значення.

vector = np.arange(1, 11)
print("Одновимірний масив:", vector)


Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та
# виведіть його значення.

matrix_3x3_zeros = np.zeros((3, 3), dtype=np.int8)
print("Двовимірний масив 3x3, заповнений нулями:\n", matrix_3x3_zeros)


Двовимірний масив 3x3, заповнений нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в
# діапазоні від 1 до 10 та виведіть його значення.

matrix_5x5_random_int = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5, заповнений випадковими цілими числами:\n",
      matrix_5x5_random_int)


Масив розміром 5x5, заповнений випадковими цілими числами:
 [[ 5  1  7  5  9]
 [ 6  8  2  1 10]
 [ 7  2  2  1  9]
 [ 9  6  2  5  5]
 [ 1  5  2  1  1]]


In [5]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та виведіть його значення.

matrix_4x4_random_float = np.random.rand(4, 4)
print("Масив розміром 4x4, заповнений випадковими дійсними числами:\n",
      matrix_4x4_random_float)


Масив розміром 4x4, заповнений випадковими дійсними числами:
 [[0.63467081 0.99397829 0.30875195 0.57618275]
 [0.81731277 0.69153335 0.02426768 0.08618486]
 [0.08625085 0.4114128  0.81505062 0.75818753]
 [0.4884143  0.54342604 0.67080972 0.39380503]]


In [6]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
# числами в діапазоні від 1 до 10 та виконайте на них поелементні операції
# додавання, віднімання та множення.

vector1 = np.random.randint(1, 11, size=5)
vector2 = np.random.randint(1, 11, size=5)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

addition = vector1 + vector2
subtraction = vector1 - vector2
multiplication = vector1 * vector2

print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Вектор 1: [10  9  9  2  5]
Вектор 2: [4 3 2 2 9]
Додавання: [14 12 11  4 14]
Віднімання: [ 6  6  7  0 -4]
Множення: [40 27 18  4 45]


In [7]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх
# скалярний добуток.

vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product)

Скалярний добуток: 3.4407309438437172


In [8]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими
# числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_2x2, matrix_2x3)
print("Матриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)
print("Добуток матриць:\n", matrix_product)


Матриця 2x2:
 [[8 6]
 [1 6]]
Матриця 2x3:
 [[ 1 10 10]
 [ 3  2  4]]
Добуток матриць:
 [[ 26  92 104]
 [ 19  22  34]]


In [9]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("Матриця 3x3:\n", matrix_3x3)
print("Обернена матриця:\n", inverse_matrix)


Матриця 3x3:
 [[10  3  8]
 [ 2  1 10]
 [10  8  2]]
Обернена матриця:
 [[ 0.17567568 -0.13063063 -0.04954955]
 [-0.21621622  0.13513514  0.18918919]
 [-0.01351351  0.11261261 -0.00900901]]


In [10]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та транспонуйте її.

matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = matrix_4x4.T
print("Матриця 4x4:\n", matrix_4x4)
print("Транспонована матриця:\n", transposed_matrix)


Матриця 4x4:
 [[0.35531579 0.40511551 0.33361808 0.73091107]
 [0.23675817 0.75096008 0.55831585 0.61553518]
 [0.87771016 0.8249978  0.91307486 0.60866509]
 [0.24186669 0.85857426 0.42486023 0.48807872]]
Транспонована матриця:
 [[0.35531579 0.23675817 0.87771016 0.24186669]
 [0.40511551 0.75096008 0.8249978  0.85857426]
 [0.33361808 0.55831585 0.91307486 0.42486023]
 [0.73091107 0.61553518 0.60866509 0.48807872]]


In [11]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
product_matrix_vector = np.dot(matrix_3x4, vector_4)
print("Матриця 3x4:\n", matrix_3x4)
print("Вектор розміром 4:", vector_4)
print("Добуток матриці та вектора:", product_matrix_vector)


Матриця 3x4:
 [[ 7  4  3  8]
 [ 3  9  3  2]
 [ 6  9 10  7]]
Вектор розміром 4: [ 2  7  9 10]
Добуток матриці та вектора: [149 116 235]


In [12]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими
# дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
product_matrix_vector = np.dot(matrix_2x3, vector_3)
print("Матриця 2x3:\n", matrix_2x3)
print("Вектор розміром 3:", vector_3)
print("Добуток матриці та вектора:", product_matrix_vector)


Матриця 2x3:
 [[0.15517611 0.16387501 0.33072642]
 [0.79420103 0.04057547 0.43592712]]
Вектор розміром 3: [0.87214566 0.72741226 0.09786631]
Добуток матриці та вектора: [0.28690783 0.76483665]


In [13]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

matrix1_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2_2x2 = np.random.randint(1, 11, size=(2, 2))
elementwise_product = matrix1_2x2 * matrix2_2x2
print("Матриця 1 (2x2):\n", matrix1_2x2)
print("Матриця 2 (2x2):\n", matrix2_2x2)
print("Поелементне множення:\n", elementwise_product)


Матриця 1 (2x2):
 [[9 3]
 [5 6]]
Матриця 2 (2x2):
 [[2 1]
 [5 6]]
Поелементне множення:
 [[18  3]
 [25 36]]


In [14]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть їх добуток.

matrix1_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(matrix1_2x2, matrix2_2x2)
print("Матриця 1 (2x2):\n", matrix1_2x2)
print("Матриця 2 (2x2):\n", matrix2_2x2)
print("Добуток матриць:\n", matrix_product)


Матриця 1 (2x2):
 [[3 2]
 [3 9]]
Матриця 2 (2x2):
 [[ 5 10]
 [ 7  8]]
Добуток матриць:
 [[ 29  46]
 [ 78 102]]


In [15]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в
# діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix_5x5)
print("Матриця 5x5:\n", matrix_5x5)
print("Сума елементів матриці:", sum_elements)


Матриця 5x5:
 [[ 92  24  56  79  54]
 [ 46  90  27 100  85]
 [ 16   7  71  56  39]
 [ 79  90   8  20  24]
 [ 13  46  52   6  95]]
Сума елементів матриці: 1275


In [16]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix1_4x4 = np.random.randint(1, 11, size=(4, 4))
matrix2_4x4 = np.random.randint(1, 11, size=(4, 4))
difference_matrix = matrix1_4x4 - matrix2_4x4
print("Матриця 1 (4x4):\n", matrix1_4x4)
print("Матриця 2 (4x4):\n", matrix2_4x4)
print("Різниця матриць:\n", difference_matrix)


Матриця 1 (4x4):
 [[ 3  1  5  8]
 [ 2  3  2  4]
 [10  3  9  7]
 [ 6  9  1  8]]
Матриця 2 (4x4):
 [[ 5  3  1  2]
 [ 7  1  5  8]
 [10  2  9  9]
 [ 7  8  9  1]]
Різниця матриць:
 [[-2 -2  4  6]
 [-5  2 -3 -4]
 [ 0  1  0 -2]
 [-1  1 -8  7]]


In [17]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів
# кожного рядка матриці.

matrix_3x3 = np.random.rand(3, 3)
row_sum = np.sum(matrix_3x3, axis=1)
print("Матриця 3x3:\n", matrix_3x3)
print("Сума елементів кожного рядка:", row_sum)


Матриця 3x3:
 [[0.28172064 0.09690354 0.70000059]
 [0.06168842 0.3848692  0.73123213]
 [0.25183719 0.25506383 0.06000974]]
Сума елементів кожного рядка: [1.07862476 1.17778976 0.56691076]


In [18]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з
# квадратами цих чисел.

matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
matrix_square = np.square(matrix_3x4)
print("Матриця 3x4:\n", matrix_3x4)
print("Квадрат елементів матриці:\n", matrix_square)


Матриця 3x4:
 [[10  3  9  2]
 [ 8 10  3  8]
 [ 7  7  8  2]]
Квадрат елементів матриці:
 [[100   9  81   4]
 [ 64 100   9  64]
 [ 49  49  64   4]]


In [19]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в
# діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

vector_4 = np.random.randint(1, 51, size=4)
vector_sqrt = np.sqrt(vector_4)
print("Вектор розміром 4:", vector_4)
print("Квадратний корінь вектора:", vector_sqrt)


Вектор розміром 4: [ 7  6 44 45]
Квадратний корінь вектора: [2.64575131 2.44948974 6.63324958 6.70820393]
